<?php if( sizeof($this->getTotals()) > 0 ): ?>
<?php
    $last = '';
    $total = array();
    foreach($this->getTotals() as $_total):
        $words = explode(' ',$_total['label']);
        $total[$words[0]][] = $_total;
    endforeach;
 ?>
<div class="box" id="dashboard_diagram_totals">
    <?php foreach( $total as $label => $_auxtotal ): ?>
    <div class="entry-edit">
        <div class="entry-edit-head"><h4><?php echo $label ?></h4></div>
        <table cellspacing="0" width="100%">
            <tr>
                <?php foreach( $_auxtotal as $_total ): ?>
                <td class="a-center bold">
                    <span><?php echo $_total['label'] ?></span><br />
                    <span class="nowrap" style="font-size:18px; color:#EA7601;"><?php echo $_total['value'] ?><span style="font-size:14px; color:#DE8946;"><?php echo $_total['decimals'] ?></span></span>
                </td>
                <?php endforeach; ?>
            </tr>
        </table>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
